name: mac release

on: push

jobs:
  build:
    name: Compile
    runs-on: macos-14
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Compile
        if: startsWith(github.ref, 'refs/tags/')
        run: | 
            brew install sfml dylibbundler
            (cd src && make OS=Darwin release)

      - name: Create DMG
        if: startsWith(github.ref, 'refs/tags/')
        run: make tar.gz dmg

      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ${{ github.workspace }}/*.tar.gz
            ${{ github.workspace }}/*.dmg
            ${{ github.workspace }}/*.dmg.sparseimage