name: windows release

on: push

jobs:
  build:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Compile
        run: (cd src && make OS=Mingw release)

      - name: Run Release
        if: startsWith(github.ref, 'refs/tags/')
        run: make release-mingw

      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ${{ github.workspace }}/*.zip 