name: linux release

on: push

jobs:
  build:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Run Release
        if: startsWith(github.ref, 'refs/tags/')
        run: | 
            sudo apt update -y && sudo apt install libfuse2 libsfml-dev -y
            (cd src && make release)

      - name: Get Tag Name
        id: get_tag_name
        run: echo "::set-output name=tag_name::${GITHUB_REF#refs/tags/}"

      - name: Get Architecture
        id: get_architecture
        run: echo "::set-output name=arch::$(uname -m)"

      - name: Create AppImage
        id: create_appimage
        run: |
          EXE=super_mario_kart
          # Setup
          APPDIR=appdir
          mkdir $APPDIR
          cp -r assets LICENSE README.md $EXE $APPDIR
          # builder
          ARCH=`uname -m`
          wget -q "https://github.com/linuxdeploy/linuxdeploy/releases/download/1-alpha-20240109-1/linuxdeploy-$ARCH.AppImage"
          chmod a+x linuxdeploy-$ARCH.AppImage
          # build AppImage
          ./linuxdeploy-$ARCH.AppImage --executable $EXE --appdir $APPDIR --output appimage --desktop-file assets/smk.desktop --icon-file assets/icon.ico 

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ github.workspace }}/*.AppImage