name: mac release

on: push

jobs:
  build:
    name: Compile
    runs-on: macos-14
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Release
        run: make release-mac tar.gz

      - name: Update Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ${{ github.workspace }}/*.tar.gz
            ${{ github.workspace }}/*.dmg
            ${{ github.workspace }}/*.dmg.sparseimage