name: windows release

on: push

jobs:
  build:
    name: Compile
    runs-on: windows-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install MinGW
        run: |
          choco install mingw --version=13.1.0 -y

      - name: Download and Install SFML
        shell: bash
        run: |
          curl -L -o SFML.zip https://www.sfml-dev.org/files/SFML-2.6.1-windows-gcc-13.1.0-mingw-64-bit.zip
          unzip SFML.zip
          mv SFML-2.6.1 /c/SFML
          rm SFML.zip
  
      - name: Download and Install libFLAC
        shell: bash
        run: |
          cd /tmp
          curl -L -o flac.tar.xz https://github.com/xiph/flac/releases/download/1.4.3/flac-1.4.3.tar.xz
          tar -xf flac.tar.xz
          cd flac-1.4.3
          ./configure --host=x86_64-w64-mingw32 --disable-shared --enable-static
          make
          cp ./src/libFLAC/.libs/libFLAC.a /c/SFML/lib/
  
      - name: Run Release
        # if: startsWith(github.ref, 'refs/tags/')
        run: | 
            (cd src && make OS=Windows_NT release)

      - name: Create Zip
        # if: startsWith(github.ref, 'refs/tags/')
        id: create_zip
        run: make zip

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        # if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ${{ github.workspace }}/*.zip 